# Generated by Django 5.2.8 on 2026-03-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDb',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DNAStrand1', models.CharField(max_length=5)),
                ('DNAStrand2', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ParentDb',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DNAStrand1', models.CharField(max_length=5)),
                ('DNAStrand2', models.CharField(max_length=5)),
            ],
        ),
    ]
